"""remove test table

Revision ID: 99fb601d5b6d
Revises: 94b540128288
Create Date: 2023-08-24 19:23:53.744560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fb601d5b6d'
down_revision: Union[str, None] = '94b540128288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_id', table_name='test')
    op.drop_index('ix_test_title', table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.create_index('ix_test_title', 'test', ['title'], unique=False)
    op.create_index('ix_test_id', 'test', ['id'], unique=False)
    # ### end Alembic commands ###
